### ISSUE TITLE
Web UI Credentials

### ISSUE THREAD

**Issue by csulit** [6ixfalls/railway-rabbitmq#1]
May I know the default user pass for the web view? thanks

**Comment by 6ixfalls** [comment]
It's randomly generated. Check the RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS variables in the RabbitMQ service.

**Comment by csulit** [comment]
> It's randomly generated. Check the RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS variables in the RabbitMQ service.

I appreciate your response. Thank you.
